### Register device
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Switch",
  "mACAddress": "80-86-F2-02-A0-2G",
  "uplinkMACAddress": "80-86-F2-02-A0-2G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-02-A0-1G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Gateway",
  "mACAddress": "80-86-F2-02-A0-0G",
  "uplinkMACAddress": "80-86-F2-02-A0-2G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Gateway",
  "mACAddress": "80-86-F2-02-A0-0F",
  "uplinkMACAddress": "80-86-F2-02-A0-2G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Gateway",
  "mACAddress": "80-86-F2-02-A0-0D",
  "uplinkMACAddress": "80-86-F2-02-A0-2G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-02-00-0D",
  "uplinkMACAddress": "80-86-F2-02-A0-0F"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-12-00-0D",
  "uplinkMACAddress": "80-86-F2-02-00-0D"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-22-00-0D",
  "uplinkMACAddress": "80-86-F2-12-00-0D"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "81-86-F2-32-00-0D",
  "uplinkMACAddress": "80-86-F2-22-00-0D"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "82-86-F2-32-00-0D",
  "uplinkMACAddress": "80-86-F2-22-00-0D"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-32-00-0D",
  "uplinkMACAddress": "80-86-F2-22-00-0D"
}


### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-86-F2-42-00-0D",
  "uplinkMACAddress": "80-86-F2-32-00-0D"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-76-F2-02-A0-1G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-66-F2-02-A0-1G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "80-56-F2-02-A0-1G"
}

### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "70-86-F2-42-00-0D",
  "uplinkMACAddress": "80-56-F2-02-A0-1G"
}
### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "60-86-F2-42-00-0D",
  "uplinkMACAddress": "80-56-F2-02-A0-1G"
}
### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "50-86-F2-42-00-0D",
  "uplinkMACAddress": "80-56-F2-02-A0-1G"
}
### Register device no uplink
POST http://localhost:8765/networkdeployment
Content-Type: application/json

{
  "deviceType": "Access Point",
  "mACAddress": "40-86-F2-42-00-0D",
  "uplinkMACAddress": "80-56-F2-02-A0-1G"
}
